name: Start a release

on:
  push:
    tags:
      - 'release-[0-9]+.[0-9]+.[0-9]+'

concurrency: prepare-for-a-release

jobs:
  update-melpa-version:
    name: Update .el versions
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ponylang/shared-docker-ci-emacs-mode-release:20241204
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Start release process
        run: bash .ci-scripts/release/update-melpa-version.bash
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  start-a-release:
    name: Start a release
    runs-on: ubuntu-latest
    needs: [update-melpa-version]
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Start
        uses: docker://ponylang/release-bot-action:0.5.0
        with:
          step: start-a-release
          GIT_USER_NAME: "Ponylang Main Bot"
          GIT_USER_EMAIL: "ponylang.main@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
